repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        stages: [commit]
        always_run: False
-   repo: https://github.com/hhatto/mirrors-autopep8
    rev: v2.0.2
    hooks:
    -   id: autopep8 # ignore rules to workaround issues linting markdown in jupytext notebooks
        args: ["-i", "--ignore=W291, E402, E501"]  # ignore trailing ws, code before imports, and line length
        files: ^(src|notebooks|{{ cookiecutter.package_name }})\/.*py$
        stages: [commit]
        always_run: False
-   repo: https://github.com/python-poetry/poetry
    rev: 1.7.1  # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["-vv"]
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
        verbose: True
